[deps]
DelayDiffEq = "bcd4f6db-9728-5f36-b5f7-82caef46ccdb"
FiniteStatePopulationDynamics = "c910fb8b-fb88-47fe-a579-bc7a7e1444df"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StructuredPopulationCore = "33358fd2-7d60-4541-bded-caea801370e0"

[sources]
FiniteStatePopulationDynamics = {path = ".."}
StructuredPopulationCore = {path = "../../StructuredPopulationCore.jl"}
